pipeline {
    agent {
        node {
            label 'maven-slaves'
        }
    }
    environment {
        PATH = "/opt/apache-maven-3.9.2/bin:$PATH"
        scannerHome = tool 'jkhan-sonarqube-scanner'
        MAVEN_OPTS = '-Xmx2048m'
    }

    stages {
        stage('Build') {
            steps {
                dir('tweet_java_app') {
                    sh '''
                        mvn clean deploy -Dmaven.test.skip=true
                    '''
                }
            }
        stage('Test') {
            steps {
                dir('tweet_java_app') {
                    sh '''
                    mvn sunfire-report:report
                    '''
                }
            }
        }
 
        }

        stage('SonarQube Analysis') {
            steps {
                dir('tweet_java_app') {
                    withSonarQubeEnv('jkhan-sonarqube-server') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=ttrend01_trendapp \
                            -Dsonar.organization=ttrend01 \
                            -Dsonar.sources=src/main/java \
                            -Dsonar.java.binaries=target/classes \
                            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                            -Dsonar.java.libraries=target/*.jar \
                            -Dsonar.sourceEncoding=UTF-8 \
                            -Dsonar.language=java \
                            -Dsonar.java.source=1.8
                        """
                    }
                }
            }
        }


    }

    post {
        always {
            cleanWs()
        }
        failure {
            echo 'Pipeline failed'
        }
        unstable {
            echo 'Pipeline unstable'
        }
        success {
            echo 'Pipeline succeeded'
        }
    }
}
