pipeline {
    agent {
        node {
            label 'maven-slaves'
        }
    }
    environment {
        PATH = "/opt/apache-maven-3.9.2/bin:$PATH"
        scannerHome = tool 'jkhan-sonarqube-scanner'
        MAVEN_OPTS = '-Xmx2048m'
    }

    stages {
        stage('Build') {
            steps {
                dir('tweet_java_app') {
                    sh '''
                        mvn clean install -Dmaven.test.skip=true
                    '''
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('tweet_java_app') {
                    sh '''
                        mvn test
                    '''
                }
            }
        }

           stage("Sonar Analysis") {
            environment {
                scannerHome = tool 'valaxy-sonarscanner'
            }
            steps {
                echo "<--------------- Sonar Analysis started -------------->"
                withSonarQubeEnv('valaxy-sonarqube-server') {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
                echo "<--------------- Sonar Analysis completed -------------->"
            }
        }

           stage("Quality Gate") {
            steps {
                script {
                    echo "<--------------- Sonar Gate Analysis Started -------------->"
                    timeout(time: 1, unit: 'HOURS') {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline failed due to quality gate failures: ${qg.status}"
                        }
                    }
                    echo "<--------------- Sonar Gate Analysis completed -------------->"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        failure {
            echo 'Pipeline failed'
        }
        unstable {
            echo 'Pipeline unstable'
        }
        success {
            echo 'Pipeline succeeded'
        }
    }
}
